apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
    spec:
      containers:
      - name: ml-inference
        image: ml-inference:v7
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8001
        resources:
          requests:
            cpu: "1"
            memory: "1G"
          limits:
            cpu: "1"
            memory: "1G"
