apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatcher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dispatcher
  template:
    metadata:
      labels:
        app: dispatcher
    spec:
      containers:
      - name: dispatcher
        image: dispatcher:v7
        imagePullPolicy: Never
        ports:
        - name: http
          containerPort: 8000
